import TranscriptTool from "@/components/transcript-tool";
import ChromeExtensionLink from "@/components/chrome-extension-link";
import { BULKTRANSCRIPTS_URL, CHROME_EXTENSION_URL, SITE_NAME, SITE_URL } from "@/lib/constants";

const faq = [
  ["Is YouTube To Transcript free to use?", "Yes. Paste one public YouTube video and start without an account or credit card. Fair-use limits protect the free service. For channels and playlists, use BulkTranscripts."],
  ["How do I access the transcript after generating it?", "The transcript appears directly below the video. You can search it, copy it, turn timestamps on or off, or download TXT, SRT and VTT files."],
  ["Can I translate the transcript to other languages?", "The tool returns the caption language available for the video. Translation and larger language workflows are available through BulkTranscripts."],
  ["Is there a limit to the length of the video I can transcribe?", "Long videos generally work when YouTube provides captions, although retrieval time depends on the video's caption track."],
  ["How long does it take to generate the transcript?", "Most captioned videos appear in a few seconds. Previously requested videos may load faster from the shared cache."],
  ["Can I download the transcript?", "Yes. Download clean text as TXT or timestamped captions as SRT and VTT."],
  ["Do you offer a YouTube Transcript API?", "Yes. BulkTranscripts provides a developer API and MCP server for processing channels, playlists and larger collections."],
];

const softwareSchema = { "@context": "https://schema.org", "@type": "WebApplication", name: SITE_NAME, url: SITE_URL, applicationCategory: "UtilitiesApplication", operatingSystem: "Any", description: "Generate a readable transcript from one YouTube video for free.", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, creator: { "@type": "Organization", name: "BulkTranscripts", url: BULKTRANSCRIPTS_URL } };
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };

function Mark() { return <span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 32 32"><rect x="4.5" y="6" width="23" height="19" rx="5" fill="none" stroke="currentColor" strokeWidth="2.2" /><path d="M10 12.5h12M10 17h8M10 21.5h5" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" /></svg></span>; }

export default function Home() {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} />
    <header className="site-header"><button className="menu-button" aria-label="Open menu"><span /><span /><span /></button><a className="brand" href="#top" aria-label="YouTube2Transcript home"><Mark /><span>YouTube<span>2</span>Transcript</span></a><a className="header-link" href={`${BULKTRANSCRIPTS_URL}/?source=youtube2transcript`}>Need bulk transcripts? <span>↗</span></a></header>
    <main id="top">
      <section className="hero"><div className="bookmark-badge"><kbd>⌘</kbd><b>+</b><kbd>D</kbd> Bookmark us!</div><h1>YouTube to Transcript</h1><p className="hero-copy">Generate YouTube Transcript for FREE.<br />Access available transcript languages, easy copy and edit.</p><TranscriptTool /><div className="chrome-cta"><span className="chrome-icon">●</span>{CHROME_EXTENSION_URL ? <ChromeExtensionLink href={CHROME_EXTENSION_URL} /> : <span><strong>Add to Chrome</strong><small>Coming soon — get transcript without leaving YouTube!</small></span>}</div><div className="benefits"><span>▣ One-click Copy</span><span>文 Supports Translation</span><span>◎ Multiple Languages</span></div></section>
      <a className="bulk-banner" href={`${BULKTRANSCRIPTS_URL}/?source=youtube2transcript`}>〈/〉 &nbsp; Need a YouTube Transcript API? Try BulkTranscripts with low bulk pricing <b>→</b></a>
      <section className="seo-content" id="how-it-works"><h2 className="color-heading purple">Effortlessly Generate YouTube Transcripts with Copy and Translation Features! 🚀</h2><p>Use YouTube2Transcript to extract the transcript from any public YouTube video. Get clean text, search it, copy it, and download it in useful formats.</p><h2 className="color-heading violet">New Features 😎</h2><ul><li><strong>Easy copy:</strong> Copy the complete transcript in one click.</li><li><strong>Timestamped lines:</strong> Jump to the exact moment in the embedded video.</li><li><strong>Multiple formats:</strong> Save TXT, SRT or VTT files.</li></ul><h2 className="color-heading pink">How to Generate a YouTube Transcript 🎥</h2><ol><li>Paste the YouTube video link and click “Get Transcript.”</li><li>Search, copy or toggle timestamps in the result.</li><li>Download the transcript or send the text to your notes and AI tools.</li></ol><h3 className="try-heading">Try it below 👇</h3><TranscriptTool /><h2 className="color-heading purple">Why you need YouTube Transcript? 🤔</h2><p>YouTube videos are invaluable for learning and entertainment, but sometimes reading is faster than watching. A transcript helps with note-taking, research, accessibility, quotations and content planning.</p><h2 className="color-heading green">For Note Takers 📝</h2><p>Copy a lecture, interview or podcast into your notes—or paste it into ChatGPT, Claude or NotebookLM to create summaries, questions and study guides.</p><h2 className="color-heading yellow">Pair YouTube Transcripts with AI tools 🤖</h2><p>Turn the transcript into key points, quizzes, quotes, blog posts, social content and more. Need an entire playlist or channel? <a className="inline-link" href={`${BULKTRANSCRIPTS_URL}/app?source=youtube2transcript`}>Use BulkTranscripts for bulk extraction →</a></p></section>
      <section className="faq-section" id="faq"><h2 className="color-heading green">FAQ</h2><div className="faq-list">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span>⌄</span></summary><p>{answer}</p></details>)}</div></section><a className="bottom-cta" href="#top">Get YouTube Transcript For Free!</a>
    </main>
    <footer className="site-footer"><a className="brand" href="#top"><Mark /><span>YouTube<span>2</span>Transcript</span></a><p>Built by the team behind <a href={BULKTRANSCRIPTS_URL}>BulkTranscripts.co</a>. Independent service, not affiliated with YouTube or Google.</p><div><a href={`${BULKTRANSCRIPTS_URL}/docs`}>API</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="mailto:sneakyguysaas@gmail.com">Contact</a></div></footer>
  </>;
}
