import TranscriptTool from "@/components/transcript-tool";
import ChromeExtensionLink from "@/components/chrome-extension-link";
import SiteMenu from "@/components/site-menu";
import { BraveIcon, ChromeIcon } from "@/components/browser-icons";
import { BULKTRANSCRIPTS_URL, CHROME_EXTENSION_URL, SITE_NAME, SITE_URL } from "@/lib/constants";

const faq = [
  ["Is YouTube to Transcript free to use?", "Yes. Paste one public YouTube video and get the transcript without an account or credit card. Fair-use limits keep the free service running for everyone. For 100+ videos, a channel or a playlist, use BulkTranscripts."],
  ["How do I get the transcript of a YouTube video?", "Copy the video link from YouTube, paste it into the box above and press Get transcript. The text appears below the video within a few seconds when the video has captions."],
  ["Does it work on videos without captions?", "No. The tool reads the caption track YouTube already has for the video, so a video with captions disabled and no auto-generated track returns nothing. It does not generate speech-to-text."],
  ["Can I download the transcript?", "Yes. Download clean text as TXT, or timed captions as SRT or VTT. Copy also works with timestamps on or off."],
  ["Can I get the transcript in another language?", "You can pick any caption language the video already has. The tool does not translate; if you need translated or bulk transcripts, BulkTranscripts covers larger workflows."],
  ["Is there a limit on video length?", "Long videos work as long as YouTube provides captions. A three-hour podcast takes a little longer to load than a ten-minute clip, that is all."],
  ["Do you offer a YouTube transcript API?", "Yes, through BulkTranscripts: a REST API and a hosted MCP server that handle channels, playlists and large collections, with 30 free credits to start."],
];

const softwareSchema = { "@context": "https://schema.org", "@type": "WebApplication", name: SITE_NAME, url: SITE_URL, applicationCategory: "UtilitiesApplication", operatingSystem: "Any", description: "Generate a readable transcript from one YouTube video for free.", image: `${SITE_URL}/opengraph-image`, browserRequirements: "Requires JavaScript", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, creator: { "@type": "Organization", name: "BulkTranscripts", url: BULKTRANSCRIPTS_URL } };
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };

function Mark() { return <span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 32 32"><rect x="4.5" y="6" width="23" height="19" rx="5" fill="none" stroke="currentColor" strokeWidth="2.2" /><path d="M10 12.5h12M10 17h8M10 21.5h5" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" /></svg></span>; }

export default function Home() {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema).replace(/</g, "\\u003c") }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} />
    <header className="site-header"><SiteMenu /><a className="brand" href="#top" aria-label="YouTube2Transcript home"><Mark /><span>YouTube<span>2</span>Transcript</span></a><a className="header-link" href={`${BULKTRANSCRIPTS_URL}/?source=youtube2transcript`} aria-label="Need bulk transcripts? Open BulkTranscripts"><em>Need bulk transcripts?</em> <span>↗</span></a></header>
    <main id="top">
      <section className="hero"><div className="bookmark-badge"><kbd>Ctrl</kbd><b>/</b><kbd>⌘</kbd><b>+</b><kbd>D</kbd> Bookmark us!</div><h1>Free YouTube to Transcript</h1><p className="hero-copy">Paste a YouTube link, get the transcript as text. Free, no sign-up.<br />Search it, copy it, or download TXT, SRT and VTT.</p><TranscriptTool /><div className="chrome-cta"><span className="browser-icons"><ChromeIcon /><BraveIcon /></span><ChromeExtensionLink href={CHROME_EXTENSION_URL} /></div><div className="benefits"><span>▣ One-click copy</span><span>◷ Timestamps on or off</span><span>◎ Every caption language</span></div></section>
      <a className="bulk-banner" href={`${BULKTRANSCRIPTS_URL}/?source=youtube2transcript`}>〈/〉 &nbsp; Need a YouTube Transcript API? Try BulkTranscripts with low bulk pricing <b>→</b></a>
      <section className="seo-content" id="how-it-works"><h2 className="color-heading purple">What you get from a YouTube video</h2><p>YouTube2Transcript turns one public YouTube video into readable text. It reads the video&rsquo;s own caption track, whether the creator wrote it or YouTube generated it, cleans up the caption fragments into sentences, and shows the result under the video. You can search inside it, toggle timestamps, copy the whole thing, or download it as a TXT, SRT or VTT file. No account, no card, no watermark.</p><h2 className="color-heading violet">How to get a YouTube transcript in three steps</h2><ol><li>Copy the video link from YouTube. Watch links, share links and Shorts links all work.</li><li>Paste it above and press <strong>Get transcript</strong>. Captioned videos usually appear in a few seconds.</li><li>Search, copy with or without timestamps, or download the file you need.</li></ol><h3 className="try-heading">Try it here</h3><TranscriptTool idPrefix="second" /><h2 className="color-heading pink">Which file to download</h2><ul><li><strong>TXT</strong> is plain text, one line per caption, for notes, documents and pasting into ChatGPT, Claude or NotebookLM.</li><li><strong>SRT</strong> keeps the start and end time of every line, for video editors and re-uploading captions.</li><li><strong>VTT</strong> is the web caption format for HTML5 players and browser extensions.</li></ul><h2 className="color-heading green">Languages and timestamps</h2><p>The tool returns whichever caption languages YouTube has for the video and lets you pick one. It does not translate: a Spanish video with only Spanish captions gives you Spanish text. Timestamps can be switched on when you need to quote a moment and off when you want clean reading text, and the copied text follows the switch.</p><h2 className="color-heading yellow">Why read instead of watch</h2><p>A one-hour lecture is a ten-minute read. Transcripts make a video searchable, quotable and easy to skim, and they are the fastest way to give an AI assistant the content of a video: paste the text into ChatGPT, Claude or NotebookLM and ask for a summary, a study guide, or the three points that matter. Students, researchers, journalists and people who prefer reading all use it the same way.</p><h2 className="color-heading purple">What it cannot do</h2><p>If a video has no captions at all, there is nothing to read and the tool says so rather than inventing text. Private and members-only videos are not reachable. And this page handles one video at a time by design: for a whole playlist or channel, or for hundreds of videos in one file, use <a className="inline-link" href={`${BULKTRANSCRIPTS_URL}/app?source=youtube2transcript`}>BulkTranscripts</a>, which is built by the same team for exactly that.</p></section>
      <section className="faq-section" id="faq"><h2 className="color-heading green">FAQ</h2><div className="faq-list">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span>⌄</span></summary><p>{answer}</p></details>)}</div></section><a className="bottom-cta" href="#top">Get YouTube Transcript For Free!</a>
    </main>
    <footer className="site-footer"><a className="brand" href="#top"><Mark /><span>YouTube<span>2</span>Transcript</span></a><p>Built by the team behind <a href={BULKTRANSCRIPTS_URL}>BulkTranscripts.co</a>. Independent service, not affiliated with YouTube or Google.</p><div><a href={`${BULKTRANSCRIPTS_URL}/docs`}>API</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="mailto:hello@bulktranscripts.co">Contact</a></div></footer>
  </>;
}
